### ISSUE TITLE
Leverage this

### ISSUE THREAD

**Issue by deb-sandeep** [vivekkant/portfolio-utils#2]
Vivek, please have a look at [CapitalystServer](https://github.com/deb-sandeep/CapitalystServer). You should be able to leverage most of the code.

**Comment by vivekkant** [comment]
> Vivek, please have a look at [CapitalystServer](https://github.com/deb-sandeep/CapitalystServer). You should be able to leverage most of the code.

Sure Sandy will have a look. More than the need it is just something to keep my coding urges satisfied :)
